In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [5]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

creating Arrays

In [7]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [9]:
type(my_list)

list

In [11]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
type(arr)

numpy.ndarray

In [15]:
type(my_list)

list

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.arange(3.0)

array([0., 1., 2.])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
np.arange(20,10)

array([], dtype=int32)

In [29]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [31]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [33]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [37]:
np.arange(30,20)

array([], dtype=int32)

In [39]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [41]:
np.arange(10,10)

array([], dtype=int32)

In [45]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [47]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [49]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [51]:
np.zeros(3)

array([0., 0., 0.])

In [53]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [55]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [57]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [59]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [61]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [63]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [67]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [71]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [75]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [77]:
n

(6, 7)

In [79]:
n1

(6, 8)

In [81]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [83]:
np.ones(3)

array([1., 1., 1.])

In [85]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [87]:
np.ones(4)

array([1., 1., 1., 1.])

In [89]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [91]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [93]:
np.twos((2,3), dtype=int)

AttributeError: module 'numpy' has no attribute 'twos'

In [95]:
np.tthrees((2,3))

AttributeError: module 'numpy' has no attribute 'tthrees'

In [97]:
np.ones(2)

array([1., 1.])

In [101]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [103]:
np.ones((6,10),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [105]:
range(5)

range(0, 5)

In [107]:
r=range(5)
r

range(0, 5)

In [109]:
for i in r:
    print(i)

0
1
2
3
4


In [111]:
list(range(5))

[0, 1, 2, 3, 4]

In [113]:
range(1,10)

range(1, 10)

In [115]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [117]:
list(range(1,10,3))

[1, 4, 7]

In [119]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [121]:
rand(3,2)

NameError: name 'rand' is not defined

In [123]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [125]:
np.random.rand(5)

array([0.32705167, 0.52144864, 0.6310611 , 0.19318161, 0.47843811])

In [127]:
np.random.rand(2,4)

array([[0.40015269, 0.16691043, 0.65556662, 0.7927126 ],
       [0.76348395, 0.86208715, 0.39086106, 0.96558168]])

In [129]:
np.random.randint(2,4)

2

In [133]:
np.random.randint(2,20)

19

In [135]:
np.random.randint(0,1)

0

In [138]:
np.random.randint(10,20,5)

array([19, 18, 14, 18, 15])

In [140]:
np.random.randint(1,6,4)

array([5, 2, 3, 3])

In [142]:
np.random.rand(3)

array([0.31031724, 0.67712162, 0.19805303])

In [144]:
np.random.randint(1)

0

In [146]:
np.random.randint(-30,20,10) 

array([ -5, -21,   4,  19,  12, -19,  -5, -23,  15,  10])

In [148]:
np.random.randint(20,30,10) 

array([20, 24, 22, 20, 21, 24, 20, 26, 28, 23])

In [150]:
np.random.randint(5,9)

5

In [152]:
np.random.randint(10,21,3)

array([13, 19, 15])

In [154]:
np.random.randint(1,12,10)

array([11,  5,  4,  7,  1,  4,  7,  3,  5,  9])

In [156]:
np.random.randint(10,40,(10,10))

array([[36, 38, 27, 25, 27, 38, 19, 31, 23, 35],
       [12, 31, 24, 10, 28, 26, 14, 10, 22, 18],
       [32, 17, 29, 29, 32, 24, 26, 18, 25, 34],
       [10, 19, 12, 19, 32, 20, 18, 29, 16, 38],
       [37, 34, 14, 20, 20, 26, 34, 31, 34, 15],
       [11, 14, 32, 38, 18, 16, 31, 19, 33, 22],
       [34, 10, 31, 16, 25, 13, 37, 33, 34, 20],
       [20, 20, 38, 37, 36, 17, 39, 31, 12, 24],
       [20, 37, 33, 31, 11, 37, 38, 10, 13, 38],
       [16, 39, 15, 29, 21, 35, 23, 19, 14, 23]])

In [158]:
np.random.randint(1,100,(12,12))

array([[18, 74, 46, 61, 23, 62, 74, 89, 34, 42, 33, 60],
       [37, 75, 91, 89, 76, 53, 41, 44, 34,  6, 34,  5],
       [61, 89, 96, 99, 95, 77, 35, 24, 14, 82, 64, 53],
       [23, 95,  8, 62, 16, 78, 19, 32, 51, 65, 94,  7],
       [73, 32, 95,  9, 10,  3,  2, 74, 47, 57, 17, 52],
       [33, 66, 18, 62, 93, 46, 83, 55, 28, 57, 66,  1],
       [34, 46, 88, 45, 59, 64, 48,  2, 37, 46, 46,  9],
       [84, 16, 95, 93, 11, 37, 89, 34, 53, 77, 24, 66],
       [39, 28, 70, 80, 99, 98, 18, 38, 26, 77, 62, 33],
       [51, 21, 77, 53, 66, 17, 49,  6, 76, 60, 37, 32],
       [80,  3, 72, 23, 84, 23, 78,  6, 35, 96, 56,  8],
       [19, 75, 25,  6, 40, 32, 42, 60, 73, 46, 74,  2]])

In [160]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [162]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [164]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [166]:
type(b)

numpy.ndarray

In [168]:
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [170]:
b[:]

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [172]:
b[1:3]

array([[12, 14, 16, 15],
       [14, 18, 19, 15]])

In [174]:
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [176]:
b[1,2]

16

In [178]:
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [180]:
b[1,3]

15

In [182]:
b[1,-1]

15

In [184]:
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [188]:
b[2:3]

array([[14, 18, 19, 15]])

In [190]:
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [192]:
b[0:-2]

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15]])

In [194]:
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [198]:
b[0,2]

11

In [200]:
b[-5,-3]

15

In [202]:
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [204]:
b[-4,2]

16

In [206]:
np.random.randint(10,20,(4,4))

array([[17, 11, 16, 17],
       [10, 15, 15, 15],
       [19, 13, 15, 17],
       [17, 15, 12, 12]])

In [208]:
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [212]:
b[-4,-2]

16

In [214]:
b

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [216]:
b[-4:2]

array([[12, 14, 16, 15]])

In [218]:
b[:]

array([[17, 15, 11, 16],
       [12, 14, 16, 15],
       [14, 18, 19, 15],
       [11, 18, 19, 10],
       [12, 11, 17, 14]])

In [220]:
a = np.random.randint(10,20,10)
a

array([10, 12, 16, 13, 12, 15, 17, 13, 19, 17])

In [222]:
id(a)

2749344680528

In [224]:
arr

array([0, 1, 2, 3, 4, 5])

In [226]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [33, 76, 73, 25,  1, 30, 91, 44, 12, 60]])

In [228]:
arr

array([0, 1, 2, 3, 4, 5])

In [230]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [232]:
arr

array([0, 1, 2, 3, 4, 5])

In [234]:
arr2[:]

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [33, 76, 73, 25,  1, 30, 91, 44, 12, 60]])

In [236]:
arr

array([0, 1, 2, 3, 4, 5])

In [238]:
arr[:4]

array([0, 1, 2, 3])

In [240]:
arr2[:]

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [33, 76, 73, 25,  1, 30, 91, 44, 12, 60]])

In [242]:
arr2[0:5]

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93]])

In [244]:
arr2

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [33, 76, 73, 25,  1, 30, 91, 44, 12, 60]])

In [246]:
arr2[1,4]

76

In [248]:
arr2

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [33, 76, 73, 25,  1, 30, 91, 44, 12, 60]])

In [250]:
arr2[-5,5]

20

In [252]:
arr2[-5,-5]

20

In [254]:
arr2

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [33, 76, 73, 25,  1, 30, 91, 44, 12, 60]])

In [258]:
arr2[-1,-2]

12

In [260]:
arr2

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [33, 76, 73, 25,  1, 30, 91, 44, 12, 60]])

In [262]:
arr2[::-1]

array([[33, 76, 73, 25,  1, 30, 91, 44, 12, 60],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [46,  5, 64, 10, 48, 61, 20, 89, 33, 67]])

In [264]:
arr2

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [33, 76, 73, 25,  1, 30, 91, 44, 12, 60]])

In [266]:
arr2[::-2]

array([[33, 76, 73, 25,  1, 30, 91, 44, 12, 60],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96]])

In [268]:
arr2[::-3]

array([[33, 76, 73, 25,  1, 30, 91, 44, 12, 60],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [46,  5, 64, 10, 48, 61, 20, 89, 33, 67]])

In [270]:
arr2

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54],
       [15, 81, 61, 48,  7, 16, 74, 74, 17, 57],
       [ 0, 95, 74, 51, 83, 12, 71, 63, 35, 80],
       [33, 76, 73, 25,  1, 30, 91, 44, 12, 60]])

In [272]:
arr2[:-3]

array([[46,  5, 64, 10, 48, 61, 20, 89, 33, 67],
       [41, 56,  3, 67, 76, 21, 99, 25, 80, 96],
       [59, 91, 23, 86, 77, 89, 87, 28, 52, 59],
       [45, 52, 87,  7, 30, 46, 30, 46, 73, 18],
       [38, 42, 43, 69, 82,  4, 24, 33, 28, 93],
       [38, 77, 33, 96, 43, 20, 66, 37, 92, 47],
       [65, 45, 45, 70, 55, 68, 83,  5, 39, 54]])

In [274]:
arr

array([0, 1, 2, 3, 4, 5])

In [276]:
arr.max()

5

In [278]:
arr.min()

0

In [280]:
arr

array([0, 1, 2, 3, 4, 5])

In [282]:
arr.mean()

2.5

In [284]:
arr

array([0, 1, 2, 3, 4, 5])

In [286]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [288]:
arr

array([0, 1, 2, 3, 4, 5])

In [290]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [292]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [294]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [296]:
arr

array([0, 1, 2, 3, 4, 5])

In [300]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [302]:
arr.reshape(2,3,order='F') 

array([[0, 2, 4],
       [1, 3, 5]])

In [304]:
arr

array([0, 1, 2, 3, 4, 5])

In [306]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [308]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [310]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [312]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [314]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [316]:
arr.reshape(4,1)

ValueError: cannot reshape array of size 6 into shape (4,1)

In [318]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [320]:
arr

array([0, 1, 2, 3, 4, 5])

In [322]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [326]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [336]:
row-4
col=5

NameError: name 'row' is not defined

In [334]:
row

NameError: name 'row' is not defined

In [338]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [344]:
row = 4
col = 5


In [342]:
row

4

In [346]:
col

5

In [348]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [350]:
mat[row,col] 

45

In [352]:
mat[4,5]

45

In [354]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [356]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [358]:
col=6

In [360]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [362]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [364]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [366]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [368]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [370]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [372]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [374]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [378]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [380]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [382]:
row

4

In [384]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [388]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [391]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [394]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [396]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [398]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [400]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [402]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [404]:
row

4

In [406]:
col

6

In [408]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [410]:
mat[1,4]

14

In [412]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [414]:
mat[3,-3]

37

In [416]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [418]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [420]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [422]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [424]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [426]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [428]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [430]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [432]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [434]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [436]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [438]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [440]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [442]:
mat[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [444]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [446]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [448]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [450]:
mat[0,1]

1

In [452]:
mat[1,6]

16

In [454]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [456]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [458]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [460]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [462]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [464]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [466]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [468]:
mat[3,5]

35

In [470]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [472]:
mat[1:2,2:4] 

array([[12, 13]])

In [474]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [476]:
mat[2:3,2:3]

array([[22]])

In [478]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [480]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [482]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [484]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [486]:
mat[2:3,4:5]

array([[24]])

In [488]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [490]:
id(mat)

2749359412336

In [492]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [494]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [496]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [498]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [502]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [504]:
mat[mat==50]

array([50])

In [506]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [508]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [510]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [512]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [514]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [516]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [518]:
a4 = mat[mat==50] 
a4

array([50])

In [533]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

otp_length = 4 
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 4004


In [535]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [537]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [539]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000028022710D40>


In [541]:
list1

['a', 'b', 'g', 1, 5]

In [543]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
