In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
print("Array a:",a)

Array a: [1 2 3]


In [9]:
b=np.arange(0,10,2)
print("Array b:",b)

Array b: [0 2 4 6 8]


In [11]:
d=np.zeros((2,3))
print("Array d:",d)

Array d: [[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
f=np.eye(4)
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [19]:
f1=np.array([[1,2],[3,4]])
flattened=np.ravel(f1)
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [21]:
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(f1)
print("Transposed array:", transposed)

Transposed array: [[1 3]
 [2 4]]


In [23]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])
print("Stacked arrays :\n", stacked)

Stacked arrays :
 [[1 2]
 [3 4]]


In [27]:
g=np.array([1,2,3,4])
added=np.add(g,2)
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [31]:
squared=np.power(g,2)
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [35]:
sqrt_val=np.sqrt(g)
print("Square root of g:",sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [37]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [41]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,a)
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


In [43]:
print(a1)
print(a)

[1 2 3]
[1 2 3]


In [47]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [49]:
std_dev=np.std(s)
print("Standard deviation of s:",std_dev)

Standard deviation of s: 1.118033988749895


In [51]:
minimum=np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [53]:
maximum=np.max(s)
print("Max of s:", maximum)

Max of s: 4


In [57]:
matrix=np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [59]:
random_vals=np.random.rand(3)
print("Random Values:",random_vals)

Random Values: [0.6730746  0.23835153 0.18681152]


In [61]:
np.random.seed(0)
random_vals=np.random.rand(3)
print("Random Values:", random_vals)

Random Values: [0.5488135  0.71518937 0.60276338]


In [72]:
rand_ints=np.random.randint(0,10,size=5)
print("Random Integers:", rand_ints)

Random Integers: [8 1 6 7 7]


In [74]:
np.random.seed(0)
rand_ints=np.random.randint(0,10,size=5)
print("Random Integers:", rand_ints)

Random Integers: [5 0 3 3 7]


In [5]:
import numpy as np

In [7]:
logical_test=np.array([True,False,True])
all_true=np.all(logical_test)
print("All Elements True:", all_true)

All Elements True: False


In [9]:
logical_test=np.array([False,False,False])
all_true=np.all(logical_test)
print("All Elements True:", all_true)

All Elements True: False


In [15]:
any_true = np.any(logical_test)  
print("Any elements True:", any_true)

Any elements True: False


In [21]:
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])
Intersection=np.intersect1d(set_a,set_b)
print("Intersection of a and b:", Intersection)

Intersection of a and b: [3 4]


In [23]:
Union=np.union1d(set_a,set_b)
print("Union of a and b:", Union)

Union of a and b: [1 2 3 4 5 6]


In [25]:
a=np.array([1,2,3])
shape=a.shape
size=a.size
dimensions=a.ndim
dtype=a.dtype
print("Shape of a:", shape)
print("Shape of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data Type of a:", dtype)


Shape of a: (3,)
Shape of a: 3
Number of dimensions of a: 1
Data Type of a: int32


In [29]:
a=np.array([1,2,3])
copied_array=np.copy(a)
print("Copied Array:", copied_array)

Copied Array: [1 2 3]


In [31]:
array_size_in_bytes=a.nbytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [33]:
shared=np.shares_memory(a,copied_array)
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
