1.Numpy Code

In [1]:
import numpy as np

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
newarr1 = arr.reshape(2, 3, 2) 
newarr2 = arr.reshape(4,3)
print(newarr1)
print(newarr2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
newarr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [11]:
newarr1 = [...,2]
print(newarr1)

[Ellipsis, 2]


In [13]:
import numpy as np

In [15]:
b = np.arange(0,20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
b1 = np.reshape(b,(5,4))
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [19]:
b1[0,0]

0

In [21]:
b1[-1]

array([16, 17, 18, 19])

In [23]:
b1[1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [25]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
b1>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [29]:
b1<15

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [31]:
a = np.array([ [ 0, 1, 2, 3, 4],[10,11,12,13,14],[20,21,22,23,24],[30,31,32,33,34] ])
c = np.array( [True,False,True,False] ) 
print(a)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [33]:
c

array([ True, False,  True, False])

In [35]:
a[c,:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [37]:
d =  np.array([False,True,True,False,True])  # boolean column selector
a[:,d]

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24],
       [31, 32, 34]])

In [39]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [51]:
i = np.array([0, 1, 2, 1])
j = np.array([1,2,3,3]) 

In [53]:
a[i,j]

array([ 1, 12, 23, 13])

In [55]:
a[i]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14]])

In [57]:
a[j]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [30, 31, 32, 33, 34]])

In [59]:
a[i,j]

array([ 1, 12, 23, 13])

In [62]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

3. abs() & 4. ABSOLUTE 

In [64]:
import numpy as np

In [66]:
ARR = np.arange(-4,5).reshape(3,3)
ARR

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [72]:
abs(ARR)

array([[4, 3, 2],
       [1, 0, 1],
       [2, 3, 4]])

In [74]:
ARR1 = 1.2 + 5j
ARR1

(1.2+5j)

In [76]:
abs(ARR1)

5.141984052872976

In [78]:
np.absolute(ARR1)

5.141984052872976

In [82]:
np.absolute([-10,-15])

array([10, 15])

5. accumulate

In [84]:
import numpy as np

In [86]:
A1 = np.arange(0,10) 
print(A1)

[0 1 2 3 4 5 6 7 8 9]


In [88]:
np.add.accumulate(A1)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [90]:
A2 = np.arange(1,6)

In [92]:
A2

array([1, 2, 3, 4, 5])

In [94]:
np.multiply.accumulate(A2)

array([  1,   2,   6,  24, 120])

In [96]:
AC = np.array([[1,2,3],[4,5,6]])
AC

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
np.add.accumulate(AC)

array([[1, 2, 3],
       [5, 7, 9]])

In [102]:
np.multiply.accumulate(AC)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

6. add

In [105]:
import numpy as np

In [107]:
ar1 = [2, -6]
ar2 = [1, 3]
ar3 = [2.2, 8.7]
ar4 = [7, -3]
print(ar1, ar2, ar3,  ar4)

[2, -6] [1, 3] [2.2, 8.7] [7, -3]


In [109]:
np.add(ar1, ar2)

array([ 3, -3])

In [111]:
np.add(ar3, ar4)

array([9.2, 5.7])

In [113]:
c1=5+2j
c1


(5+2j)

In [115]:
np.add(ar3,c1)

array([ 7.2+2.j, 13.7+2.j])

7. All

In [117]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.all(a>5)

False

In [121]:
np.all(a>=0)

True

In [123]:
b7 = np.array([True, False, True, True])
np.all(b7)

False

8. Allclose

In [125]:
np.allclose([0.1, 0.003], [0.11, 0.003])

False

In [127]:
np.allclose([0.11, 0.0033], [0.11000005, 0.00330001])

True

In [129]:
np.allclose([1e10,1e-8], [1.0001e10,1e-9])

False

In [131]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

9. alltrue

In [133]:
b = np.array([True, False, True, True])
np.alltrue(b)

False

In [135]:
a = np.array([1, 5, 2, 7])
np.alltrue(a >= 5)

False

In [137]:
np.alltrue(a>0)

True

10.Angle

In [139]:
np.angle([5+3j, 1j, 1.0])

array([0.5404195 , 1.57079633, 0.        ])

In [141]:
np.angle([5+3j, 1j, 1.0], deg=True)

array([30.96375653, 90.        ,  0.        ])

In [147]:
np.angle(1+1j,deg=True)

45.0

In [145]:

np.angle(1+1j,deg=False)

0.7853981633974483

11. Any

In [149]:
c2 = np.array([True, False, True])

In [151]:
np.any(c2)

True

In [153]:
c3= np.arange(0,10)
c3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
any(c3>=5)

True

12. Append

In [157]:
c3= np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

In [159]:
c3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
c5 =np.append(c3, 10)
c5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
np.append(c5, ('ABC', 1 +2j))

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'ABC', '(1+2j)'],
      dtype='<U64')

In [165]:
c9= np.arange(10, 61, 10)
c9

array([10, 20, 30, 40, 50, 60])

In [167]:
np.append(c9, (70, 80, 90))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [169]:
c10 =np.reshape(c9, (2,3))
c10

array([[10, 20, 30],
       [40, 50, 60]])

In [173]:
c11 = np.append(c10, [[70, 80, 90]], axis = 0)
c11

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [175]:
c13 = np.append(c11, [[100], [120], [130]], axis = 1) 
c13

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 120],
       [ 70,  80,  90, 130]])

13. apply_along_axis

In [177]:
def func1(Q): 
    return (Q[0] + Q[-1])
abc = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
abc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [179]:
np.apply_along_axis(func1,0,abc)

array([ 8, 10, 12])

In [181]:
np.apply_along_axis(func1,1,abc)

array([ 4, 10, 16])

In [183]:
def func2(P): #2
    return (P[0] + P[-1])*2
abc1 = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
abc1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
np.apply_along_axis(func2,0,abc1)

array([16, 20, 24])

In [187]:
np.apply_along_axis(func2,1,abc1)

array([ 8, 20, 32])

In [189]:
D = np.arange(24)
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [191]:
D=np.reshape(D, (2,3,4))
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [193]:
DQ = np.apply_over_axes(np.sum, D, [0,2])
DQ

array([[[ 60],
        [ 92],
        [124]]])

15. arrange

In [195]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [197]:
np.arange(11.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [201]:
np.arange(8, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [203]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [205]:
np.arange(3,30,9)

array([ 3, 12, 21])

16. arccos

In [207]:
np.arccos([1, -1]) 

array([0.        , 3.14159265])

17. arccosh

In [209]:
np.arccosh([np.e, 10.0])

array([1.65745445, 2.99322285])

In [211]:
np.arccosh(1)

0.0

18. arcsin

In [213]:
np.arcsin([1, -1, 0])

array([ 1.57079633, -1.57079633,  0.        ])

20. arctan

In [215]:
np.arctan([0, 1, -1])

array([ 0.        ,  0.78539816, -0.78539816])

21. arctan2

In [217]:
x = np.array([-1, +1, +1, -1])
y = np.array([-1, -1, +1, +1])
np.arctan2(y, x) * 180 / np.pi 

array([-135.,  -45.,   45.,  135.])

In [219]:
np.arctan2(y, x)

array([-2.35619449, -0.78539816,  0.78539816,  2.35619449])

In [221]:
np.arctan2([1., -1.], [0., 0.])

array([ 1.57079633, -1.57079633])

In [223]:
np.arctan2([0, 1], [1, 0])

array([0.        , 1.57079633])

22. arctanh

In [225]:
np.arctanh([0, -0.5])

array([ 0.        , -0.54930614])

23. argmax

In [227]:
J =np.array([0, 11, 95, 2, -5, 55])

In [230]:
j

array([1, 2, 3, 3])

In [232]:
np.argmax(J)

2

In [234]:
j1 = np.arange(6).reshape(2,3) +10
j1

array([[10, 11, 12],
       [13, 14, 15]])

In [236]:
np.argmax(j1)

5

In [242]:
j2=np.array([[10,50,30],[60,20,60]])
j2

array([[10, 50, 30],
       [60, 20, 60]])

In [248]:
J2 = np.array([[1, 9, 0, 4], [2, 0, 8, -1]])
J2

array([[ 1,  9,  0,  4],
       [ 2,  0,  8, -1]])

In [250]:
np.argmax(J2, axis =0) 

array([1, 0, 1, 0], dtype=int64)

In [252]:
np.argmax(J2, axis =1)

array([1, 2], dtype=int64)

In [256]:
d4 =np.array([0, 11, 95, 2, -5, 55]) 
d4

array([ 0, 11, 95,  2, -5, 55])

In [258]:
np.argmin(d4)

4

In [260]:
da2=np.array([[50,50,10],[60,10,40]])
da2

array([[50, 50, 10],
       [60, 10, 40]])

In [262]:
np.argmin(da2)

2

In [264]:
np.argmin(da2, axis=0)

array([0, 1, 0], dtype=int64)

In [266]:
np.argmin(da2, axis=1)

array([2, 1], dtype=int64)

In [270]:
AB1 = np.array([ 2, 0,  1, 5, 4, 1, 9])
AB1

array([2, 0, 1, 5, 4, 1, 9])

In [272]:
np.argsort(AB1)

array([1, 2, 5, 0, 4, 3, 6], dtype=int64)

In [274]:
BQ = np.argsort(AB1)
BQ

array([1, 2, 5, 0, 4, 3, 6], dtype=int64)

In [276]:
AB1[BQ]

array([0, 1, 1, 2, 4, 5, 9])

In [286]:
aq1 = np.array([[8,4,1],[2,0,9]])
aq1

array([[8, 4, 1],
       [2, 0, 9]])

In [280]:
JQ1 = aq1.argsort(axis=0)
JQ1

array([[1, 1, 0],
       [0, 0, 1]], dtype=int64)

In [282]:
aq1[JQ1,[[0,1,2], [0,1,2]]]

array([[2, 0, 1],
       [8, 4, 9]])

In [284]:
JQ1 = aq1.argsort(axis=1)
JQ1 

array([[2, 1, 0],
       [1, 0, 2]], dtype=int64)

26. array

In [288]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [290]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [292]:
np.array([1, 2, 3], dtype=complex) 

array([1.+0.j, 2.+0.j, 3.+0.j])

In [294]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [296]:
np.array(1, copy=0, subok=1, ndmin=1)

array([1])

In [298]:
np.array(1, copy=0, subok=1, ndmin=2)

array([[1]])

In [300]:
np.array(1, subok=1, ndmin=2)

array([[1]])

28. array split

In [302]:
c4 = np.array([[1,2,3,4],[5,6,7,8]])
c4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [304]:
np.array_split(c4,2,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [308]:
np.array_split(c4,4,axis=1)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [310]:
np.array_split(c4,3,axis=1)

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [312]:
np.array_split(c4,[2,3],axis=1)

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

29. asarray

In [314]:
my_list = [1, 3, 5, 7, 9]
np.asarray(my_list)

array([1, 3, 5, 7, 9])

In [316]:
my_tuple = ([1, 3, 9], [8, 2, 6])
np.asarray(my_tuple)

array([[1, 3, 9],
       [8, 2, 6]])

In [318]:
m = np.matrix('1 2; 5 8')
m

matrix([[1, 2],
        [5, 8]])

In [320]:
B9 = np.asarray(m)
B9

array([[1, 2],
       [5, 8]])

In [322]:
m[0,1] = -190
m

matrix([[   1, -190],
        [   5,    8]])

In [324]:
B9

array([[   1, -190],
       [   5,    8]])

30. asanyarray

In [326]:
c7 = np.array([[1,2],[5,8]])
c7

array([[1, 2],
       [5, 8]])

In [328]:
mq = np.matrix('1 2; 5 8')
mq

matrix([[1, 2],
        [5, 8]])

In [330]:
np.asanyarray(c7)

array([[1, 2],
       [5, 8]])

In [332]:
np.asanyarray(mq)

matrix([[1, 2],
        [5, 8]])

In [336]:
my_tuple1 = ([1, 3, 9], [8, 2, 6])
my_tuple1

([1, 3, 9], [8, 2, 6])

In [338]:
np.asanyarray(my_tuple1)

array([[1, 3, 9],
       [8, 2, 6]])

31. asmatrix

In [340]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [342]:
x[0,0] = 5
print(m)
print(x)

[[5 2]
 [3 4]]
[[5 2]
 [3 4]]


In [344]:
x6 = np.array([1, 2, 2.5])
x6

array([1. , 2. , 2.5])

In [346]:
x6.astype(int)

array([1, 2, 2])

In [350]:
x6.astype(None)

array([1. , 2. , 2.5])

33. atleast 1d

In [352]:
a01 = 1 
b01 = np.array([2,3]) 
c01 = np.array([[4,5],[6,7]]) 
d01 = np.arange(8).reshape(2,2,2) 
d01

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [354]:
np.atleast_1d(a01,b01,c01,d01)

[array([1]),
 array([2, 3]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

34. atleast_2d()

In [356]:
a11 = 1
b11 = np.array([2,3])
c11 = np.array([[4,5],[6,7]])
d11 = np.arange(8).reshape(2,2,2)
d11

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [358]:
np.atleast_2d(a11,b11,c11,d11)

[array([[1]]),
 array([[2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

35. atleast_3d()

In [360]:
f = 1 
g = np.array([2,3])
h = np.array([[4,5],[6,7]])
i = np.arange(8).reshape(2,2,2)
i

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [362]:
np.atleast_3d(f,g,h,i)

[array([[[1]]]),
 array([[[2],
         [3]]]),
 array([[[4],
         [5]],
 
        [[6],
         [7]]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

36. Average

In [364]:
bz = np.array([1,4,5,7,5])
bz

array([1, 4, 5, 7, 5])

In [366]:
np.average(bz)

4.4

In [370]:
w = np.array([0.1, 0.2, 0.5, 0.2, 0.2])
w

array([0.1, 0.2, 0.5, 0.2, 0.2])

In [372]:
np.average(bz,weights=w)

4.833333333333333